### ISSUE TITLE
Need magic link

### ISSUE THREAD

**Issue by coolaj86** [therootcompany/libauth.js#3]
1. User should be able to sign in without using an (insecure) password.
2. If they get their password wrong, just send a magic link
3. Forgot password flow

- [ ] Audit Log: which device was used login

Three uses
- Verification
- Magic Link
- Password Reset

Three scenarios with tabs / devices:
- [x] Start and Verify in same browser on desktop
    - caveat: might not be able to close original window
    - https://www.thesitewizard.com/javascripts/close-browser-tab-or-window.shtml
    - or maybe we can...
    - https://jeffclayton.wordpress.com/2015/02/13/javascript-window-close-method-that-still-works/
- [x] Start and Verify in same browser on mobile
- [x] Start and Verify in different browsers (desktop or mobile)

**Comment by ryanburnette** [comment]
Entering a wrong password going straight into magic link flow is a beautiful idea. 👍

**Comment by coolaj86** [comment]
Note: I've decided that initiating the magic link on login failure is actually a front-end concern.

This is due to the difficulty of error and status code handling on the case of failed-to-login-but-succeeded-to-send-magic-link.

So basically: Just make the magic link request on failure.
